epochs: 20
val_frequency: 1
learning_rate: 0.0024435492580773227
results_metric_path: results.json
optimizer: 'adam' # 'adam', 'sgd' or 'asgd'
lr_scheduler: 'cosine' # 'cosine', 'multistep_lr', 'cosine_annealing'
loss: 'CE' # 'focal', 'CE'
experiment_path: 'experiments'

model_name: resnet18.a1_in1k

num_classes: 2

pred_detections_pth: '/workspaces/scene_classification/pred_boxes_42.json'
bbox_infer_dataset: '/workspaces/scene_classification/bbox_labels_infer_squared'
annotations_pth: 'instances_val.json'

gamma: 4.491033147723654
alpha: 0.9840537807632129

w2: 0.5
w1: 0.5

weight_decay: 0

dataset:
  train:
    image_path: 'video_type_dataset'
    #image_path: 'bbox_labels_train_squared_lt_detected_png_true'
    #image_path: 'bbox_labels_overfit'
    batch_size: 1
    shuffle: True
    num_workers: 1
    img_size: 180
    center_crop: 
      ratio: 0.6
    random_invert:
      apply: True
      p: 0.3

  val:
    image_path: 'video_type_dataset'
    batch_size: 1
    shuffle: False
    num_workers: 1
    img_size: 180
    center_crop: 
      ratio: 0.6
    crop:
      ratio: 0.5
      type: 'upper-left'


  augmentations: 
    - type: "RandomHorizontalFlip"
      parameters: {}
      probability: 0.5
    - type: "RandomPhotometricDistort"
      parameters: 
        brightness: [0.8, 1.2]
        contrast: [0.8, 1.2]
        saturation: [0.8, 1.2]
      probability: 0.5
    - type: "ColorJitter"
      parameters:
        brightness: [0.8, 1.2]
        contrast: [0.8, 1.2]
        saturation: [0.8, 1.2]
        hue: 0
      probability: 0.3
    - type: "RandomRotation"
      parameters:
        degrees: [0, 15]
      probability: 0.4
    - type: "RandomResizedCrop"
      parameters:
        size: 180
        scale: [0.2, 0.8]
      probability: 1
      
  val_augmentations: 

